### ISSUE TITLE
Add sudoku datasets to repository

### ISSUE THREAD

**Issue by Emerentius** [attractivechaos/plb#35]
Under sudoku/incoming you reference several datasets and give links in the Readme.md. Two of those links have died already. If you have the datasets offline, could you add them to the repository for posterity? Prefererably all 4 as the remaining links may also die.

**Comment by attractivechaos** [comment]
See the [release page](https://github.com/attractivechaos/plb/releases/tag/v0). Top50000 and sudoku17 are the two most widely used test data sets. Often these two are sufficient. It is sad to see half of links to datasets and programs are now dead. It took me half an hour to finally recovered the two data sets from an old machine.
